//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Project/ActionMaps/GanshinActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GanshinActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GanshinActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GanshinActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""45103af7-4fbc-4d17-9579-dedab109dbae"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4e31bfb3-3a2a-42a0-9539-81e1e289bb60"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a75d36a8-8cde-4a7d-92c5-4992f2fc144f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpecialAction"",
                    ""type"": ""Button"",
                    ""id"": ""94f95cb6-b4a7-49a0-bd99-832c39b4886b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""bba65bc1-9ba8-4298-a388-4d316e9600f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""de74ed53-5157-4bed-b8d5-25504c1ae1ab"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""45bfd80f-33d5-4f54-8ab5-5ac39c067e90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BaseSkill"",
                    ""type"": ""Button"",
                    ""id"": ""cbcf89e7-54c8-46de-86b3-f8f4dc8daf0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BaseSkill2"",
                    ""type"": ""Button"",
                    ""id"": ""02244dc2-16ee-4a40-90ab-b0f2808f35b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UltimateSkill"",
                    ""type"": ""Button"",
                    ""id"": ""a3512e22-cf83-479c-ab01-6577ce7648da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""cd472e6b-7935-42fe-b8a7-91e2770db4d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""be3cf69b-76a4-4d2b-addc-f2311af69c24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""66e50c8d-5410-4ac6-842c-7accd43e57ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber3"",
                    ""type"": ""PassThrough"",
                    ""id"": ""36e004d0-0350-4da9-a24f-3f6d31022b6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber4"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1653e273-95da-4107-8a37-acdd621bb5aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber5"",
                    ""type"": ""PassThrough"",
                    ""id"": ""59819bf7-6622-4fef-8a14-1282d15e4183"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber6"",
                    ""type"": ""PassThrough"",
                    ""id"": ""589530a1-cf5a-4ed1-a425-7dcb52bd8d29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber7"",
                    ""type"": ""PassThrough"",
                    ""id"": ""375c3f11-45bb-414e-bcb8-f8490d610b01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber8"",
                    ""type"": ""PassThrough"",
                    ""id"": ""622cc494-d72b-44e0-b3a4-ac980dd6e758"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber9"",
                    ""type"": ""PassThrough"",
                    ""id"": ""48df1304-0c9b-4f65-a904-829f1e747549"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber0"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b34d8498-758a-4487-b540-d10bee6e5313"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""MoveKey"",
                    ""id"": ""69064acc-83e7-4056-8e3d-1d2468d4b710"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d5f831e2-9581-4b46-b292-75d3e3c77659"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""90c60e58-2b4d-48ce-a9ad-d98075186611"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6ba2d840-148a-45d8-8724-e41717fe6dbb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a3874fa0-8832-4b76-a564-69dbfdb4e137"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""402757a3-6efb-483f-b7f4-5b43b2c72c48"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3a8ace2f-2203-42fd-ac87-af52f6d9e4f4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ca38c3ca-4843-4ce9-b61d-b0efe9eada98"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a97721b2-b30c-4c04-ae89-d086cc6f1c59"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd9f6c61-60b1-4579-865a-ebe72a74f0c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c5784b7-8157-4ab0-bd79-51a02526ea6c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BaseSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aba4345d-2e0c-44d7-82e0-775bf8a74adb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UltimateSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""347fc8bc-427e-45ec-8541-3aa6fcb0ecd8"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bc54343-8443-4f5a-ae21-1a86a40fc334"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da5567e1-02a0-4bc8-865a-783fecc2692a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0ce0091-b6b2-46d7-810c-fe57413fc01c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0357a03-1d88-497b-a85c-6e26a4e5dd1a"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8094c6fb-ae90-484c-ba9a-0d36b4c9e521"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72002aea-b4b1-490e-b640-4f6169f2e5ee"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef3e2bd6-0b5e-4c2c-99e6-bb2bb066ea5b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""727debf4-a729-4a91-956b-80d3088344f2"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bd1ef2c-cfe9-47a2-b202-32bbf9bef294"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60f03f77-4bfc-4c1c-8edd-e7c925168a79"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46443412-e426-416f-8f51-8ec83a292348"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bfdc73b-1053-4a85-900a-650b356b4063"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42e7efaa-a562-47dc-aaf6-896e3126c80e"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BaseSkill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""None"",
            ""id"": ""b8dfc5c9-a7e5-41e4-8391-adb0972b96b7"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_Movement = m_PlayerMovement.FindAction("Movement", throwIfNotFound: true);
        m_PlayerMovement_Look = m_PlayerMovement.FindAction("Look", throwIfNotFound: true);
        m_PlayerMovement_SpecialAction = m_PlayerMovement.FindAction("SpecialAction", throwIfNotFound: true);
        m_PlayerMovement_Attack = m_PlayerMovement.FindAction("Attack", throwIfNotFound: true);
        m_PlayerMovement_Zoom = m_PlayerMovement.FindAction("Zoom", throwIfNotFound: true);
        m_PlayerMovement_Roll = m_PlayerMovement.FindAction("Roll", throwIfNotFound: true);
        m_PlayerMovement_BaseSkill = m_PlayerMovement.FindAction("BaseSkill", throwIfNotFound: true);
        m_PlayerMovement_BaseSkill2 = m_PlayerMovement.FindAction("BaseSkill2", throwIfNotFound: true);
        m_PlayerMovement_UltimateSkill = m_PlayerMovement.FindAction("UltimateSkill", throwIfNotFound: true);
        m_PlayerMovement_Interaction = m_PlayerMovement.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber1 = m_PlayerMovement.FindAction("ShortcutNumber1", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber2 = m_PlayerMovement.FindAction("ShortcutNumber2", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber3 = m_PlayerMovement.FindAction("ShortcutNumber3", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber4 = m_PlayerMovement.FindAction("ShortcutNumber4", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber5 = m_PlayerMovement.FindAction("ShortcutNumber5", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber6 = m_PlayerMovement.FindAction("ShortcutNumber6", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber7 = m_PlayerMovement.FindAction("ShortcutNumber7", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber8 = m_PlayerMovement.FindAction("ShortcutNumber8", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber9 = m_PlayerMovement.FindAction("ShortcutNumber9", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber0 = m_PlayerMovement.FindAction("ShortcutNumber0", throwIfNotFound: true);
        // None
        m_None = asset.FindActionMap("None", throwIfNotFound: true);
    }

    ~@GanshinActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerMovement.enabled, "This will cause a leak and performance issues, GanshinActions.PlayerMovement.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_None.enabled, "This will cause a leak and performance issues, GanshinActions.None.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private List<IPlayerMovementActions> m_PlayerMovementActionsCallbackInterfaces = new List<IPlayerMovementActions>();
    private readonly InputAction m_PlayerMovement_Movement;
    private readonly InputAction m_PlayerMovement_Look;
    private readonly InputAction m_PlayerMovement_SpecialAction;
    private readonly InputAction m_PlayerMovement_Attack;
    private readonly InputAction m_PlayerMovement_Zoom;
    private readonly InputAction m_PlayerMovement_Roll;
    private readonly InputAction m_PlayerMovement_BaseSkill;
    private readonly InputAction m_PlayerMovement_BaseSkill2;
    private readonly InputAction m_PlayerMovement_UltimateSkill;
    private readonly InputAction m_PlayerMovement_Interaction;
    private readonly InputAction m_PlayerMovement_ShortcutNumber1;
    private readonly InputAction m_PlayerMovement_ShortcutNumber2;
    private readonly InputAction m_PlayerMovement_ShortcutNumber3;
    private readonly InputAction m_PlayerMovement_ShortcutNumber4;
    private readonly InputAction m_PlayerMovement_ShortcutNumber5;
    private readonly InputAction m_PlayerMovement_ShortcutNumber6;
    private readonly InputAction m_PlayerMovement_ShortcutNumber7;
    private readonly InputAction m_PlayerMovement_ShortcutNumber8;
    private readonly InputAction m_PlayerMovement_ShortcutNumber9;
    private readonly InputAction m_PlayerMovement_ShortcutNumber0;
    public struct PlayerMovementActions
    {
        private @GanshinActions m_Wrapper;
        public PlayerMovementActions(@GanshinActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerMovement_Movement;
        public InputAction @Look => m_Wrapper.m_PlayerMovement_Look;
        public InputAction @SpecialAction => m_Wrapper.m_PlayerMovement_SpecialAction;
        public InputAction @Attack => m_Wrapper.m_PlayerMovement_Attack;
        public InputAction @Zoom => m_Wrapper.m_PlayerMovement_Zoom;
        public InputAction @Roll => m_Wrapper.m_PlayerMovement_Roll;
        public InputAction @BaseSkill => m_Wrapper.m_PlayerMovement_BaseSkill;
        public InputAction @BaseSkill2 => m_Wrapper.m_PlayerMovement_BaseSkill2;
        public InputAction @UltimateSkill => m_Wrapper.m_PlayerMovement_UltimateSkill;
        public InputAction @Interaction => m_Wrapper.m_PlayerMovement_Interaction;
        public InputAction @ShortcutNumber1 => m_Wrapper.m_PlayerMovement_ShortcutNumber1;
        public InputAction @ShortcutNumber2 => m_Wrapper.m_PlayerMovement_ShortcutNumber2;
        public InputAction @ShortcutNumber3 => m_Wrapper.m_PlayerMovement_ShortcutNumber3;
        public InputAction @ShortcutNumber4 => m_Wrapper.m_PlayerMovement_ShortcutNumber4;
        public InputAction @ShortcutNumber5 => m_Wrapper.m_PlayerMovement_ShortcutNumber5;
        public InputAction @ShortcutNumber6 => m_Wrapper.m_PlayerMovement_ShortcutNumber6;
        public InputAction @ShortcutNumber7 => m_Wrapper.m_PlayerMovement_ShortcutNumber7;
        public InputAction @ShortcutNumber8 => m_Wrapper.m_PlayerMovement_ShortcutNumber8;
        public InputAction @ShortcutNumber9 => m_Wrapper.m_PlayerMovement_ShortcutNumber9;
        public InputAction @ShortcutNumber0 => m_Wrapper.m_PlayerMovement_ShortcutNumber0;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @SpecialAction.started += instance.OnSpecialAction;
            @SpecialAction.performed += instance.OnSpecialAction;
            @SpecialAction.canceled += instance.OnSpecialAction;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @BaseSkill.started += instance.OnBaseSkill;
            @BaseSkill.performed += instance.OnBaseSkill;
            @BaseSkill.canceled += instance.OnBaseSkill;
            @BaseSkill2.started += instance.OnBaseSkill2;
            @BaseSkill2.performed += instance.OnBaseSkill2;
            @BaseSkill2.canceled += instance.OnBaseSkill2;
            @UltimateSkill.started += instance.OnUltimateSkill;
            @UltimateSkill.performed += instance.OnUltimateSkill;
            @UltimateSkill.canceled += instance.OnUltimateSkill;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @ShortcutNumber1.started += instance.OnShortcutNumber1;
            @ShortcutNumber1.performed += instance.OnShortcutNumber1;
            @ShortcutNumber1.canceled += instance.OnShortcutNumber1;
            @ShortcutNumber2.started += instance.OnShortcutNumber2;
            @ShortcutNumber2.performed += instance.OnShortcutNumber2;
            @ShortcutNumber2.canceled += instance.OnShortcutNumber2;
            @ShortcutNumber3.started += instance.OnShortcutNumber3;
            @ShortcutNumber3.performed += instance.OnShortcutNumber3;
            @ShortcutNumber3.canceled += instance.OnShortcutNumber3;
            @ShortcutNumber4.started += instance.OnShortcutNumber4;
            @ShortcutNumber4.performed += instance.OnShortcutNumber4;
            @ShortcutNumber4.canceled += instance.OnShortcutNumber4;
            @ShortcutNumber5.started += instance.OnShortcutNumber5;
            @ShortcutNumber5.performed += instance.OnShortcutNumber5;
            @ShortcutNumber5.canceled += instance.OnShortcutNumber5;
            @ShortcutNumber6.started += instance.OnShortcutNumber6;
            @ShortcutNumber6.performed += instance.OnShortcutNumber6;
            @ShortcutNumber6.canceled += instance.OnShortcutNumber6;
            @ShortcutNumber7.started += instance.OnShortcutNumber7;
            @ShortcutNumber7.performed += instance.OnShortcutNumber7;
            @ShortcutNumber7.canceled += instance.OnShortcutNumber7;
            @ShortcutNumber8.started += instance.OnShortcutNumber8;
            @ShortcutNumber8.performed += instance.OnShortcutNumber8;
            @ShortcutNumber8.canceled += instance.OnShortcutNumber8;
            @ShortcutNumber9.started += instance.OnShortcutNumber9;
            @ShortcutNumber9.performed += instance.OnShortcutNumber9;
            @ShortcutNumber9.canceled += instance.OnShortcutNumber9;
            @ShortcutNumber0.started += instance.OnShortcutNumber0;
            @ShortcutNumber0.performed += instance.OnShortcutNumber0;
            @ShortcutNumber0.canceled += instance.OnShortcutNumber0;
        }

        private void UnregisterCallbacks(IPlayerMovementActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @SpecialAction.started -= instance.OnSpecialAction;
            @SpecialAction.performed -= instance.OnSpecialAction;
            @SpecialAction.canceled -= instance.OnSpecialAction;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @BaseSkill.started -= instance.OnBaseSkill;
            @BaseSkill.performed -= instance.OnBaseSkill;
            @BaseSkill.canceled -= instance.OnBaseSkill;
            @BaseSkill2.started -= instance.OnBaseSkill2;
            @BaseSkill2.performed -= instance.OnBaseSkill2;
            @BaseSkill2.canceled -= instance.OnBaseSkill2;
            @UltimateSkill.started -= instance.OnUltimateSkill;
            @UltimateSkill.performed -= instance.OnUltimateSkill;
            @UltimateSkill.canceled -= instance.OnUltimateSkill;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @ShortcutNumber1.started -= instance.OnShortcutNumber1;
            @ShortcutNumber1.performed -= instance.OnShortcutNumber1;
            @ShortcutNumber1.canceled -= instance.OnShortcutNumber1;
            @ShortcutNumber2.started -= instance.OnShortcutNumber2;
            @ShortcutNumber2.performed -= instance.OnShortcutNumber2;
            @ShortcutNumber2.canceled -= instance.OnShortcutNumber2;
            @ShortcutNumber3.started -= instance.OnShortcutNumber3;
            @ShortcutNumber3.performed -= instance.OnShortcutNumber3;
            @ShortcutNumber3.canceled -= instance.OnShortcutNumber3;
            @ShortcutNumber4.started -= instance.OnShortcutNumber4;
            @ShortcutNumber4.performed -= instance.OnShortcutNumber4;
            @ShortcutNumber4.canceled -= instance.OnShortcutNumber4;
            @ShortcutNumber5.started -= instance.OnShortcutNumber5;
            @ShortcutNumber5.performed -= instance.OnShortcutNumber5;
            @ShortcutNumber5.canceled -= instance.OnShortcutNumber5;
            @ShortcutNumber6.started -= instance.OnShortcutNumber6;
            @ShortcutNumber6.performed -= instance.OnShortcutNumber6;
            @ShortcutNumber6.canceled -= instance.OnShortcutNumber6;
            @ShortcutNumber7.started -= instance.OnShortcutNumber7;
            @ShortcutNumber7.performed -= instance.OnShortcutNumber7;
            @ShortcutNumber7.canceled -= instance.OnShortcutNumber7;
            @ShortcutNumber8.started -= instance.OnShortcutNumber8;
            @ShortcutNumber8.performed -= instance.OnShortcutNumber8;
            @ShortcutNumber8.canceled -= instance.OnShortcutNumber8;
            @ShortcutNumber9.started -= instance.OnShortcutNumber9;
            @ShortcutNumber9.performed -= instance.OnShortcutNumber9;
            @ShortcutNumber9.canceled -= instance.OnShortcutNumber9;
            @ShortcutNumber0.started -= instance.OnShortcutNumber0;
            @ShortcutNumber0.performed -= instance.OnShortcutNumber0;
            @ShortcutNumber0.canceled -= instance.OnShortcutNumber0;
        }

        public void RemoveCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);

    // None
    private readonly InputActionMap m_None;
    private List<INoneActions> m_NoneActionsCallbackInterfaces = new List<INoneActions>();
    public struct NoneActions
    {
        private @GanshinActions m_Wrapper;
        public NoneActions(@GanshinActions wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_None; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NoneActions set) { return set.Get(); }
        public void AddCallbacks(INoneActions instance)
        {
            if (instance == null || m_Wrapper.m_NoneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NoneActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(INoneActions instance)
        {
        }

        public void RemoveCallbacks(INoneActions instance)
        {
            if (m_Wrapper.m_NoneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INoneActions instance)
        {
            foreach (var item in m_Wrapper.m_NoneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NoneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NoneActions @None => new NoneActions(this);
    public interface IPlayerMovementActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSpecialAction(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnBaseSkill(InputAction.CallbackContext context);
        void OnBaseSkill2(InputAction.CallbackContext context);
        void OnUltimateSkill(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnShortcutNumber1(InputAction.CallbackContext context);
        void OnShortcutNumber2(InputAction.CallbackContext context);
        void OnShortcutNumber3(InputAction.CallbackContext context);
        void OnShortcutNumber4(InputAction.CallbackContext context);
        void OnShortcutNumber5(InputAction.CallbackContext context);
        void OnShortcutNumber6(InputAction.CallbackContext context);
        void OnShortcutNumber7(InputAction.CallbackContext context);
        void OnShortcutNumber8(InputAction.CallbackContext context);
        void OnShortcutNumber9(InputAction.CallbackContext context);
        void OnShortcutNumber0(InputAction.CallbackContext context);
    }
    public interface INoneActions
    {
    }
}
