//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Project/Resources/ActionMaps/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""45103af7-4fbc-4d17-9579-dedab109dbae"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4e31bfb3-3a2a-42a0-9539-81e1e289bb60"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a75d36a8-8cde-4a7d-92c5-4992f2fc144f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""94f95cb6-b4a7-49a0-bd99-832c39b4886b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""bba65bc1-9ba8-4298-a388-4d316e9600f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""PassThrough"",
                    ""id"": ""45bfd80f-33d5-4f54-8ab5-5ac39c067e90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BaseSkill"",
                    ""type"": ""Button"",
                    ""id"": ""cbcf89e7-54c8-46de-86b3-f8f4dc8daf0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UltimateSkill"",
                    ""type"": ""Button"",
                    ""id"": ""a3512e22-cf83-479c-ab01-6577ce7648da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""cd472e6b-7935-42fe-b8a7-91e2770db4d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""be3cf69b-76a4-4d2b-addc-f2311af69c24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""66e50c8d-5410-4ac6-842c-7accd43e57ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber3"",
                    ""type"": ""PassThrough"",
                    ""id"": ""36e004d0-0350-4da9-a24f-3f6d31022b6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber4"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1653e273-95da-4107-8a37-acdd621bb5aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber5"",
                    ""type"": ""PassThrough"",
                    ""id"": ""59819bf7-6622-4fef-8a14-1282d15e4183"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber6"",
                    ""type"": ""PassThrough"",
                    ""id"": ""589530a1-cf5a-4ed1-a425-7dcb52bd8d29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber7"",
                    ""type"": ""PassThrough"",
                    ""id"": ""375c3f11-45bb-414e-bcb8-f8490d610b01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber8"",
                    ""type"": ""PassThrough"",
                    ""id"": ""622cc494-d72b-44e0-b3a4-ac980dd6e758"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber9"",
                    ""type"": ""PassThrough"",
                    ""id"": ""48df1304-0c9b-4f65-a904-829f1e747549"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortcutNumber0"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b34d8498-758a-4487-b540-d10bee6e5313"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""MoveKey"",
                    ""id"": ""69064acc-83e7-4056-8e3d-1d2468d4b710"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d5f831e2-9581-4b46-b292-75d3e3c77659"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""90c60e58-2b4d-48ce-a9ad-d98075186611"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6ba2d840-148a-45d8-8724-e41717fe6dbb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a3874fa0-8832-4b76-a564-69dbfdb4e137"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""28ea7e11-b3a8-464a-bf8a-012a620fe202"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a97721b2-b30c-4c04-ae89-d086cc6f1c59"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b31fa0f5-1bba-48ed-8ab0-31e59a624483"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd9f6c61-60b1-4579-865a-ebe72a74f0c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c5784b7-8157-4ab0-bd79-51a02526ea6c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BaseSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aba4345d-2e0c-44d7-82e0-775bf8a74adb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UltimateSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""347fc8bc-427e-45ec-8541-3aa6fcb0ecd8"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bc54343-8443-4f5a-ae21-1a86a40fc334"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da5567e1-02a0-4bc8-865a-783fecc2692a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0ce0091-b6b2-46d7-810c-fe57413fc01c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0357a03-1d88-497b-a85c-6e26a4e5dd1a"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8094c6fb-ae90-484c-ba9a-0d36b4c9e521"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72002aea-b4b1-490e-b640-4f6169f2e5ee"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef3e2bd6-0b5e-4c2c-99e6-bb2bb066ea5b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""727debf4-a729-4a91-956b-80d3088344f2"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bd1ef2c-cfe9-47a2-b202-32bbf9bef294"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60f03f77-4bfc-4c1c-8edd-e7c925168a79"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortcutNumber0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46443412-e426-416f-8f51-8ec83a292348"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_Movement = m_PlayerMovement.FindAction("Movement", throwIfNotFound: true);
        m_PlayerMovement_Look = m_PlayerMovement.FindAction("Look", throwIfNotFound: true);
        m_PlayerMovement_Dash = m_PlayerMovement.FindAction("Dash", throwIfNotFound: true);
        m_PlayerMovement_Attack = m_PlayerMovement.FindAction("Attack", throwIfNotFound: true);
        m_PlayerMovement_Jump = m_PlayerMovement.FindAction("Jump", throwIfNotFound: true);
        m_PlayerMovement_BaseSkill = m_PlayerMovement.FindAction("BaseSkill", throwIfNotFound: true);
        m_PlayerMovement_UltimateSkill = m_PlayerMovement.FindAction("UltimateSkill", throwIfNotFound: true);
        m_PlayerMovement_Interaction = m_PlayerMovement.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber1 = m_PlayerMovement.FindAction("ShortcutNumber1", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber2 = m_PlayerMovement.FindAction("ShortcutNumber2", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber3 = m_PlayerMovement.FindAction("ShortcutNumber3", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber4 = m_PlayerMovement.FindAction("ShortcutNumber4", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber5 = m_PlayerMovement.FindAction("ShortcutNumber5", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber6 = m_PlayerMovement.FindAction("ShortcutNumber6", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber7 = m_PlayerMovement.FindAction("ShortcutNumber7", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber8 = m_PlayerMovement.FindAction("ShortcutNumber8", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber9 = m_PlayerMovement.FindAction("ShortcutNumber9", throwIfNotFound: true);
        m_PlayerMovement_ShortcutNumber0 = m_PlayerMovement.FindAction("ShortcutNumber0", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private IPlayerMovementActions m_PlayerMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerMovement_Movement;
    private readonly InputAction m_PlayerMovement_Look;
    private readonly InputAction m_PlayerMovement_Dash;
    private readonly InputAction m_PlayerMovement_Attack;
    private readonly InputAction m_PlayerMovement_Jump;
    private readonly InputAction m_PlayerMovement_BaseSkill;
    private readonly InputAction m_PlayerMovement_UltimateSkill;
    private readonly InputAction m_PlayerMovement_Interaction;
    private readonly InputAction m_PlayerMovement_ShortcutNumber1;
    private readonly InputAction m_PlayerMovement_ShortcutNumber2;
    private readonly InputAction m_PlayerMovement_ShortcutNumber3;
    private readonly InputAction m_PlayerMovement_ShortcutNumber4;
    private readonly InputAction m_PlayerMovement_ShortcutNumber5;
    private readonly InputAction m_PlayerMovement_ShortcutNumber6;
    private readonly InputAction m_PlayerMovement_ShortcutNumber7;
    private readonly InputAction m_PlayerMovement_ShortcutNumber8;
    private readonly InputAction m_PlayerMovement_ShortcutNumber9;
    private readonly InputAction m_PlayerMovement_ShortcutNumber0;
    public struct PlayerMovementActions
    {
        private @PlayerActions m_Wrapper;
        public PlayerMovementActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerMovement_Movement;
        public InputAction @Look => m_Wrapper.m_PlayerMovement_Look;
        public InputAction @Dash => m_Wrapper.m_PlayerMovement_Dash;
        public InputAction @Attack => m_Wrapper.m_PlayerMovement_Attack;
        public InputAction @Jump => m_Wrapper.m_PlayerMovement_Jump;
        public InputAction @BaseSkill => m_Wrapper.m_PlayerMovement_BaseSkill;
        public InputAction @UltimateSkill => m_Wrapper.m_PlayerMovement_UltimateSkill;
        public InputAction @Interaction => m_Wrapper.m_PlayerMovement_Interaction;
        public InputAction @ShortcutNumber1 => m_Wrapper.m_PlayerMovement_ShortcutNumber1;
        public InputAction @ShortcutNumber2 => m_Wrapper.m_PlayerMovement_ShortcutNumber2;
        public InputAction @ShortcutNumber3 => m_Wrapper.m_PlayerMovement_ShortcutNumber3;
        public InputAction @ShortcutNumber4 => m_Wrapper.m_PlayerMovement_ShortcutNumber4;
        public InputAction @ShortcutNumber5 => m_Wrapper.m_PlayerMovement_ShortcutNumber5;
        public InputAction @ShortcutNumber6 => m_Wrapper.m_PlayerMovement_ShortcutNumber6;
        public InputAction @ShortcutNumber7 => m_Wrapper.m_PlayerMovement_ShortcutNumber7;
        public InputAction @ShortcutNumber8 => m_Wrapper.m_PlayerMovement_ShortcutNumber8;
        public InputAction @ShortcutNumber9 => m_Wrapper.m_PlayerMovement_ShortcutNumber9;
        public InputAction @ShortcutNumber0 => m_Wrapper.m_PlayerMovement_ShortcutNumber0;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnMovement;
                @Look.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnLook;
                @Dash.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnDash;
                @Attack.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnAttack;
                @Jump.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnJump;
                @BaseSkill.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnBaseSkill;
                @BaseSkill.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnBaseSkill;
                @BaseSkill.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnBaseSkill;
                @UltimateSkill.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnUltimateSkill;
                @UltimateSkill.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnUltimateSkill;
                @UltimateSkill.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnUltimateSkill;
                @Interaction.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnInteraction;
                @ShortcutNumber1.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber1;
                @ShortcutNumber1.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber1;
                @ShortcutNumber1.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber1;
                @ShortcutNumber2.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber2;
                @ShortcutNumber2.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber2;
                @ShortcutNumber2.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber2;
                @ShortcutNumber3.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber3;
                @ShortcutNumber3.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber3;
                @ShortcutNumber3.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber3;
                @ShortcutNumber4.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber4;
                @ShortcutNumber4.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber4;
                @ShortcutNumber4.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber4;
                @ShortcutNumber5.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber5;
                @ShortcutNumber5.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber5;
                @ShortcutNumber5.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber5;
                @ShortcutNumber6.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber6;
                @ShortcutNumber6.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber6;
                @ShortcutNumber6.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber6;
                @ShortcutNumber7.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber7;
                @ShortcutNumber7.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber7;
                @ShortcutNumber7.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber7;
                @ShortcutNumber8.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber8;
                @ShortcutNumber8.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber8;
                @ShortcutNumber8.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber8;
                @ShortcutNumber9.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber9;
                @ShortcutNumber9.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber9;
                @ShortcutNumber9.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber9;
                @ShortcutNumber0.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber0;
                @ShortcutNumber0.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber0;
                @ShortcutNumber0.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnShortcutNumber0;
            }
            m_Wrapper.m_PlayerMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @BaseSkill.started += instance.OnBaseSkill;
                @BaseSkill.performed += instance.OnBaseSkill;
                @BaseSkill.canceled += instance.OnBaseSkill;
                @UltimateSkill.started += instance.OnUltimateSkill;
                @UltimateSkill.performed += instance.OnUltimateSkill;
                @UltimateSkill.canceled += instance.OnUltimateSkill;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @ShortcutNumber1.started += instance.OnShortcutNumber1;
                @ShortcutNumber1.performed += instance.OnShortcutNumber1;
                @ShortcutNumber1.canceled += instance.OnShortcutNumber1;
                @ShortcutNumber2.started += instance.OnShortcutNumber2;
                @ShortcutNumber2.performed += instance.OnShortcutNumber2;
                @ShortcutNumber2.canceled += instance.OnShortcutNumber2;
                @ShortcutNumber3.started += instance.OnShortcutNumber3;
                @ShortcutNumber3.performed += instance.OnShortcutNumber3;
                @ShortcutNumber3.canceled += instance.OnShortcutNumber3;
                @ShortcutNumber4.started += instance.OnShortcutNumber4;
                @ShortcutNumber4.performed += instance.OnShortcutNumber4;
                @ShortcutNumber4.canceled += instance.OnShortcutNumber4;
                @ShortcutNumber5.started += instance.OnShortcutNumber5;
                @ShortcutNumber5.performed += instance.OnShortcutNumber5;
                @ShortcutNumber5.canceled += instance.OnShortcutNumber5;
                @ShortcutNumber6.started += instance.OnShortcutNumber6;
                @ShortcutNumber6.performed += instance.OnShortcutNumber6;
                @ShortcutNumber6.canceled += instance.OnShortcutNumber6;
                @ShortcutNumber7.started += instance.OnShortcutNumber7;
                @ShortcutNumber7.performed += instance.OnShortcutNumber7;
                @ShortcutNumber7.canceled += instance.OnShortcutNumber7;
                @ShortcutNumber8.started += instance.OnShortcutNumber8;
                @ShortcutNumber8.performed += instance.OnShortcutNumber8;
                @ShortcutNumber8.canceled += instance.OnShortcutNumber8;
                @ShortcutNumber9.started += instance.OnShortcutNumber9;
                @ShortcutNumber9.performed += instance.OnShortcutNumber9;
                @ShortcutNumber9.canceled += instance.OnShortcutNumber9;
                @ShortcutNumber0.started += instance.OnShortcutNumber0;
                @ShortcutNumber0.performed += instance.OnShortcutNumber0;
                @ShortcutNumber0.canceled += instance.OnShortcutNumber0;
            }
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);
    public interface IPlayerMovementActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnBaseSkill(InputAction.CallbackContext context);
        void OnUltimateSkill(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnShortcutNumber1(InputAction.CallbackContext context);
        void OnShortcutNumber2(InputAction.CallbackContext context);
        void OnShortcutNumber3(InputAction.CallbackContext context);
        void OnShortcutNumber4(InputAction.CallbackContext context);
        void OnShortcutNumber5(InputAction.CallbackContext context);
        void OnShortcutNumber6(InputAction.CallbackContext context);
        void OnShortcutNumber7(InputAction.CallbackContext context);
        void OnShortcutNumber8(InputAction.CallbackContext context);
        void OnShortcutNumber9(InputAction.CallbackContext context);
        void OnShortcutNumber0(InputAction.CallbackContext context);
    }
}
